# rpcrace Makefile
# Requires: config.mk (generated by ./configure)

-include config.mk

# Compiler and flags
CC       = gcc
CFLAGS   = -std=c11 -Wall -Wextra -Werror -Wpedantic -Wshadow \
           -Wstrict-prototypes -Wmissing-prototypes \
           -O2 -march=native -flto=auto -D_GNU_SOURCE \
           -Iinclude -Isrc $(ZMQ_CFLAGS)
LDFLAGS  = -flto=auto
LIBS     = -lzmq -lpthread

# Directories
SRCDIR   = src
INCDIR   = include
TESTDIR  = tests
BUILDDIR = build

# Source files
SRCS     = $(wildcard $(SRCDIR)/*.c)
OBJS     = $(patsubst $(SRCDIR)/%.c,$(BUILDDIR)/%.o,$(SRCS))

# Vendored source (yyjson)
VENDOR_SRCS = $(INCDIR)/yyjson.c
VENDOR_OBJS = $(BUILDDIR)/yyjson.o

# All objects
ALL_OBJS = $(OBJS) $(VENDOR_OBJS)

# Binary
TARGET   = rpcrace
PREFIX  ?= /usr/local

# Test sources and binaries
TEST_SRCS = $(wildcard $(TESTDIR)/*.c)
TEST_BINS = $(patsubst $(TESTDIR)/%.c,$(BUILDDIR)/%,$(TEST_SRCS))

# Default target
all: $(BUILDDIR) $(TARGET)

$(BUILDDIR):
	mkdir -p $(BUILDDIR)

# Link the binary
$(TARGET): $(ALL_OBJS)
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

# Compile source files
$(BUILDDIR)/%.o: $(SRCDIR)/%.c | $(BUILDDIR)
	$(CC) $(CFLAGS) -c -o $@ $<

# Compile vendored yyjson
$(BUILDDIR)/yyjson.o: $(INCDIR)/yyjson.c | $(BUILDDIR)
	$(CC) $(CFLAGS) -Wno-unused-function -c -o $@ $<

# Build and run tests
test: $(BUILDDIR) $(TEST_BINS)
	@echo "Running tests..."
	@failed=0; \
	for t in $(TEST_BINS); do \
		printf "  %-40s" "$$(basename $$t)"; \
		if $$t; then \
			printf "PASS\n"; \
		else \
			printf "FAIL\n"; \
			failed=$$((failed + 1)); \
		fi; \
	done; \
	if [ $$failed -gt 0 ]; then \
		echo "$$failed test(s) failed"; \
		exit 1; \
	else \
		echo "All tests passed"; \
	fi

# Compile test binaries (link against all non-main objects + vendored)
$(BUILDDIR)/%: $(TESTDIR)/%.c $(filter-out $(BUILDDIR)/main.o,$(ALL_OBJS)) | $(BUILDDIR)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< $(filter-out $<,$^) $(LIBS)

# Install
install: $(TARGET)
	install -d $(DESTDIR)$(PREFIX)/bin
	install -m 755 $(TARGET) $(DESTDIR)$(PREFIX)/bin/

# Sanitizer-enabled test run (ASan + UBSan)
sanitise: CFLAGS  += -fsanitize=address,undefined -fno-omit-frame-pointer -O1
sanitise: LDFLAGS += -fsanitize=address,undefined
sanitise: clean all test

# Clean
clean:
	rm -rf $(BUILDDIR) $(TARGET)

.PHONY: all test sanitise clean install
